INSERT INTO scrap_yards (name, location) VALUES
('desguaces tenerife', 'taco'),
('desguaces tenerife', 'sur'),
('desguaces tenerife', 'arafo'),
('desguaces polo', 'taco'),
('desguaces insulares', 'taco'),
('desguaces insulares', 'santa cruz'),
('desguaces insulares', 'los cristianos'),
('desguaces insulares', 'aguagarcia'),
('desguaces geneto', 'geneto');

INSERT INTO cars (brand, model, engine) VALUES
('bmw', 'e36 320i', 'berlina m50b20'),
('bmw', 'e36 325i', 'berlina m50b25'),
('bmw', 'e36 320i', 'coupe m50b20'),
('volkswagen', 'EOS 1F7', '2.0 TDI'),
('volkswagen', 'EOS 1F8', '2.0 TDI'),
('Seat', 'ibiza III Hatchback 6L', '1.6 16v'),
('Seat', 'ibiza III Hatchback 6L', '1.4 16v'),
('Seat', 'ibiza III Hatchback', '2.0 TDI'),
('seat', 'cordoba I sedan', '1.9D'),
('seat', 'cordoba I sedan', '1.9 SDI'),
('seat', 'cordoba I sedan', '1.0'),
('seat', 'cordoba I sedan', '1.3'),
('seat', 'cordoba I sedan', '1.4'),
('seat', 'cordoba I sedan', '1.6'),
('seat', 'cordoba I vario', '1.9 SDI'),
('seat', 'cordoba I vario', '1.9 TDI'),
('seat', 'cordoba I vario', '1.4'),
('seat', 'cordoba I vario', '1.4 16v'),
('seat', 'cordoba I vario', '1.6'),
('seat', 'cordoba I vario', '1.8'),
('citroen', 'C4 II Hatchback', '1.4 VTI'),
('Audi', '60 Sedan', '1.5'),
('Audi', '60 Variant', '1.5'),
('Audi', '75 Sedan', '1.7'),
('Audi', '45 Variant', '1.7'),
('ford', 'escort mk1 berlina', '1.6'),
('ford', 'escort mk1 berlina', '1100 1.1'),
('ford', 'escort mk1 berlina', '1.3'),
('ford', 'escort mk1 familiar', '1.6'),
('ford', 'escort mk1 familiar', '1100 1.1'),
('ford', 'escort mk1 familiar', '1.3'),
('peugeot', '104 hatchback', '0.9'),
('peugeot', '104 hatchback', '1.0'),
('peugeot', '104 hatchback', '1.1'),
('peugeot', '104 hatchback', '1.4'),
('peugeot', '104 coupe', '0.9'),
('peugeot', '104 coupe', '1.1'),
('peugeot', '104 coupe', '1.4'),
('renault', '4 familiar', '0.7'),
('renault', '4 familiar', '0.8'),
('renault', '4 familiar', '1.0'),
('renault', '4 familiar', '1.1'),
('renault', '5 hatchback', '0.8'),
('renault', '5 hatchback', '1.0'),
('renault', '5 hatchback', '1.3'),
('renault', '5 hatchback', '1.4'),
('renault', '5 hatchback', '1.4 turbo'),
('opel', 'astra F sedan', '1.7 D'),
('opel', 'astra F sedan', '1.7 TD'),
('opel', 'astra F sedan', '1.7 TDS'),
('opel', 'astra F sedan', '1.4'),
('opel', 'astra F sedan', '1.6'),
('opel', 'astra F sedan', '1.8'),
('opel', 'astra F sedan', '2.0'),
('opel', 'astra F cabrio', '1.4'),
('opel', 'astra F cabrio', '1.6'),
('opel', 'astra F cabrio', '1.8'),
('opel', 'astra F cabrio', '2.0'),
('opel', 'astra F coupe', '2.2 DTI'),
('opel', 'astra F coupe', '1.6 16v'),
('opel', 'astra F coupe', '1.8 16v'),
('opel', 'astra F coupe', '2.0 16v turbo'),
('opel', 'astra F coupe', '2.2 16v'),
('mercedes', 'AMG GT', 'C'),
('mercedes', 'AMG GT R', '4.0'),
('mercedes', 'AMG GT', 'S'),
('mercedes', 'CLA coupe', '180 CDI 1.5'),
('mercedes', 'CLA coupe', '200 CDI 2.1D'),
('mercedes', 'CLA coupe', '220 CDI D'),
('mercedes', 'CLA coupe AMG', '2.0'),
('mercedes', 'CLA familiar', '180 D'),
('mercedes', 'CLA familiar', '200 CDI'),
('mercedes', 'CLA familiar', '220 CDI'),
('mercedes', 'CLA familiar', '220 D');

INSERT INTO parts_category (category_name) VALUES
('Aire Acondicionado'),
('Sistema de Combustible'),
('Dirección'),
('Transmisión'),
('Boquillas y Mangueras'),
('Motor'),
('Carrocería'),
('Amortiguación'),
('Interior'),
('Sistema Eléctrico'),
('Sistema de Refrigeración'),
('Turbo Compresor');

INSERT INTO parts (name, car, category) VALUES 
('compresor de aire acondicionado', 1, 1),
('compresor de aire acondicionado', 1, 1),
('condensador de aire', 1, 1),
('ventilador de calefaccion', 1, 1),
('valvula de expansion de aire acondicionado', 1, 1),
('embrague de compresor', 1, 1),
('filtro deshidratador', 1, 1),
('ventilador del condensador del aire acondicionado', 1, 1),
('resistencia del ventilador', 1, 1),
('termocontacto del ventilador', 1, 1),
('valvula del control de refrigerante', 1, 1),
('filtro del habitaculo', 1, 1),
('radiador de calefaccion', 1, 1),
('evaporador de aire acondicionado', 1, 1),
('presostato de aire acondicionado', 1, 1),
('sensor de la temperatura interior', 1, 1),
('sensor de temperatura exterior', 1, 1),
('tubos de aire acondicionado', 1, 1),
('unidad de control del ventilador del radiador', 1, 1),
('bomba de combustible', 1, 2),
('inyectores', 1, 2),
('caudalimetro', 1, 2),
('junta de inyector', 1, 2),
('tubo de retorno de combustible', 1, 2),
('relé de bomba de combustible', 1, 2),
('sonda lambda', 1, 2),
('sensor tps', 1, 2),
('regulador de presion de combustible', 1, 2),
('rampa de inyeccion', 1, 2),
('filtro de combustible', 1, 2),
('carter del filtro de aceite', 1, 2),
('deposito de combustible', 1, 2),
('tapa de deposito de combustible', 1, 2),
('valvula de ralenti', 1, 2),
('cable del acelerador', 1, 2),
('sensor de nivel de combustible', 1, 2),
('rotula de direccion', 1, 3),
('rotula axial de direccion', 1, 3),
('fuelle de direccion', 1, 3),
('cremallera de direccion', 1, 3),
('rotula de suspension', 1, 3),
('bomba de direccion hidraulica', 1, 3),
('manguera hidraulica de direccion', 1, 3),
('filtro hidraulico de direccion', 1, 3),
('deposito de compensasion de direccion asistida', 1, 3),
('polea, servobomba', 1, 3),
('articulacion de la columna de direccion', 1, 3),
('suspension de la direccion', 1, 3),
('arbol de direccion', 1, 3),
('barra de direccion', 1, 3),
('barra de acoplamiento', 1, 3),
('filtro caja de cambios automatica', 1, 4),
('carter de aceite de caja de cambios', 1, 4),
('junta caja de cambios', 1, 4),
('junta carter aceite de la caja de cambios', 1, 4),
('soporte de la caja de cambios', 1, 4),
('apoyo del engranaje distribuidor', 1, 4),
('volante bimasa', 1, 4),
('palanca de selectora de cambios', 1, 4),
('interruptor de marcha atras', 1, 4),
('unidad de control de caja de cambios automatica', 1, 4),
('cojinete de la caja de cambios', 1, 4),
('manguitos del radiador', 1, 5),
('brida de refirgerante', 1, 5),
('mabguera del turbo', 1, 5),
('manguito de admision del motor', 1, 5),
('latiguillos de freno', 1, 5),
('tubo del servofreno', 1, 5),
('tuberia de frenos', 1, 5),
('tubo de refrigeracion del motor', 1, 5),
('manguito de refrigeracion del carter', 1, 5),
('conducto de aceite turbocompresor', 1, 5),
('manguito intercambiador de calor de calefaccion', 1, 5),
('latiguillo del embrague', 1, 5),
('taco de motor', 1, 6),
('correa de distribucion', 1, 6),
('correa Poly V', 1, 6),
('valvula de control de arbol de levas', 1, 6),
('piñon del arbol de levas', 1, 6),
('tensor de cadena de distribucion', 1, 6),
('ajustador de arbol de levas', 1, 6),
('carril de deslizamiento', 1, 6),
('taques hidraulicos', 1, 6),
('retenes de valvulas', 1, 6),
('tornillos de culata', 1, 6),
('valvula de escape', 1, 6),
('valvula de admision', 1, 6),
('arbol de levas', 1, 6),
('tapa de llenado de aceite', 1, 6),
('culata', 1, 6),
('tapa de valancines', 1, 6),
('reten del cigueñal', 1, 6),
('segmentos del piston', 1, 6),
('casquillos de biela', 1, 6),
('apoyo del cigueñal', 1, 6),
('tapon del carter', 1, 6),
('arandela de tapon de carter', 1, 6),
('varilla del aceite', 1, 6),
('enfriador de aceite', 1, 6),
('sensor de nivel de aceite del motor', 1, 6),
('polea tensora', 1, 6),
('tensor de correa', 1, 6),
('polea de inversion', 1, 6),
('transductor de presion', 1, 6),
('bomba de agua', 1, 6),
('vaso de expansion', 1, 6),
('radiador', 1, 6),
('ventilador del radiador', 1, 6),
('sensor de temperatura del refrigerante', 1, 6),
('embrague del ventilador', 1, 6),
('bujia de encendido', 1, 6),
('bobina de encedido', 1, 6),
('sensor de arbol de levas', 1, 6),
('cables de bujias', 1, 6),
('colector de admision', 1, 6),
('colector de escape', 1, 6),
('depresor de freno', 1, 6),
('pistones', 1, 6),
('faro principal derecho', 1, 7),
('faro principal izquierdo', 1, 7),
('faro trasero derecho', 1, 7),
('faro trasero izquierdo', 1, 7),
('espejo retrovisor derecho', 1, 7),
('espejo retrovisor izquierdo', 1, 7),
('espejo retrovisor interior', 1, 7),
('parachoques', 1, 7),
('guardabarros', 1, 7),
('capo', 1, 7),
('amortiguador de maletero', 1, 7),
('amortiguador de capo', 1, 7),
('intermitente derecho delantero', 1, 7),
('intermitente derecho trasero', 1, 7),
('intermitente izquierdo delantero', 1, 7),
('intermitente izquierdo trasero', 1, 7),
('faro antiniebla izquierdo', 1, 7),
('faro antiniebla derecho', 1, 7),
('parachoques delantero', 1, 7),
('parachoques trasero', 1, 7),
('faldones', 1, 7),
('luz de matricula', 1, 7),
('luz de freno adicional', 1, 7),
('sensor de aparcamiento', 1, 7),
('luz de marcha atras', 1, 7),
('calandra', 1, 7),
('molduras del parachoques', 1, 7),
('soporte del parachoques', 1, 7),
('refuerzo de parachoques', 1, 7),
('aletines', 1, 7),
('panel de puerta derecha', 1, 7),
('panel de puerta izquierda', 1, 7),
('panel de puerta derecha trasera', 1, 7),
('panel de puerta izquierda trasera', 1, 7),
('puerta derecha', 1, 7),
('puerta izquierda', 1, 7),
('puerta derecha trasera', 1, 7),
('puerta izquierda trasera', 1, 7),
('pomo de puerta', 1, 7),
('maletero', 1, 7),
('cierre centralizado', 1, 7),
('soporte de radiador', 1, 7),
('umbral', 1, 7),
('chapa lateral', 1, 7),
('cubierta de motor', 1, 7),
('puente', 1, 7),
('elevalunas', 1, 7),

-- Grupo 8 (categoría 8)
('amortiguador delantero derecho', 1, 8),
('amortiguador delantero izquierdo', 1, 8),
('amortiguador trasero derecho', 1, 8),
('amortiguador trasero izquierdo', 1, 8),
('copela delantero derecho', 1, 8),
('copela delantero izquierdo', 1, 8),
('copela trasero derecho', 1, 8),
('copela trasero izquierdo', 1, 8),
('guardapolvos', 1, 8),
('soporte de amortiguacion', 1, 8),
('muelle de suspension delantero', 1, 8),
('muelle de suspension trasero', 1, 8),
('caja de muelle', 1, 8),
('tornillo de ajuste de inclinacion', 1, 8),
('interruptor del elevalunas', 1, 9),
('motor del elevalunas', 1, 9),
('cerradura de puerta', 1, 9),
('bombin de cerradura', 1, 9),
('interruptor de encendido', 1, 9),
('conmutador de la columna de direccion', 1, 9),
('pedales', 1, 9),
('cuadro de instrumentos', 1, 9),
('antena', 1, 9),
('revestimiento', 1, 9),
('junta de panel de puerta', 1, 9),
('alternador', 1, 10),
('bateria', 1, 10),
('motor de arranque', 1, 10),
('motor regulador de faros', 1, 10),
('mando de luces', 1, 10),
('interruptor de luz de freno', 1, 10),
('bombilla de luz intermitente', 1, 10),
('bombilla de faro', 1, 10),
('bombilla de faro trasero', 1, 10),
('bombilla de luz larga', 1, 10),
('bomba de limpiaparabrisas', 1, 10),
('regulador del alternador', 1, 10),
('selenoide de arranque', 1, 10),
('sensor de abs', 1, 10),
('radiador', 1, 11),
('termostato', 1, 11),
('bomba de agua', 1, 11),
('brida del refrigerante', 1, 11),
('helice del ventilador', 1, 11),
('manguera de turbo', 1, 12),
('caracola de turbo', 1, 12),
('helice de turbina', 1, 12),
('valvula de descarga', 1, 12),
('mabguera de turbo', 1, 12),
('transductor de presion', 1, 12);


INSERT INTO scrap_yard_parts (part_id, scrap_yard_id, price, stock, wear_level) VALUES
  (1, 1, 200.00, TRUE, 80),
  (1, 2, 30.00, TRUE, 60);
